# Server Port
server.port=8080

# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/case_db
spring.datasource.username=postgres
spring.datasource.password=root123
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# OpenWeatherMap API Configuration
openweather.api.key=${OPENWEATHER_API_KEY}
openweathermap.api.url=https://api.openweathermap.org/data/2.5/weather?q={city}&appid={apiKey}
case.target.city=Mumbai

# JWT Security Configuration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

# Google Gemini AI Configuration
gemini.api.key=AIzaSyBO5ZfKjPKBVmgFtYGdH-vTcqJDnVdRejA
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=

news.api.key=315970c467bb4b1ca31c71b9948fdbbe
news.api.url=https://newsapi.org/v2/top-headlines?country=in&apiKey=

logging.level.org.springframework.security=DEBUG

